-- Schedule and monitor user attempt stats materialized view refreshes
CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA extensions;

CREATE TABLE IF NOT EXISTS public.user_attempt_stats_refresh_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  status text NOT NULL CHECK (status IN ('running', 'success', 'failed', 'skipped')),
  cadence_minutes integer,
  duration_ms integer,
  error_message text
);

CREATE INDEX IF NOT EXISTS idx_user_attempt_stats_refresh_logs_started_at
ON public.user_attempt_stats_refresh_logs(started_at DESC);

CREATE OR REPLACE FUNCTION public.run_user_attempt_stats_refresh_job()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_started_at timestamptz := now();
  v_last_success_finished_at timestamptz;
  v_last_success_duration_ms integer;
  v_cadence_minutes integer := 5;
  v_log_id bigint;
BEGIN
  SELECT finished_at, duration_ms
  INTO v_last_success_finished_at, v_last_success_duration_ms
  FROM public.user_attempt_stats_refresh_logs
  WHERE status = 'success'
  ORDER BY started_at DESC
  LIMIT 1;

  IF COALESCE(v_last_success_duration_ms, 0) >= 180000 THEN
    v_cadence_minutes := 15;
  ELSIF COALESCE(v_last_success_duration_ms, 0) >= 60000 THEN
    v_cadence_minutes := 10;
  END IF;

  IF v_last_success_finished_at IS NOT NULL
     AND v_started_at < v_last_success_finished_at + make_interval(mins => v_cadence_minutes) THEN
    INSERT INTO public.user_attempt_stats_refresh_logs (
      started_at,
      finished_at,
      status,
      cadence_minutes,
      duration_ms,
      error_message
    )
    VALUES (
      v_started_at,
      now(),
      'skipped',
      v_cadence_minutes,
      0,
      'Skipped by adaptive cadence gate'
    );

    RETURN;
  END IF;

  INSERT INTO public.user_attempt_stats_refresh_logs (started_at, status, cadence_minutes)
  VALUES (v_started_at, 'running', v_cadence_minutes)
  RETURNING id INTO v_log_id;

  BEGIN
    PERFORM public.refresh_user_attempt_stats_mv();

    UPDATE public.user_attempt_stats_refresh_logs
    SET
      finished_at = now(),
      status = 'success',
      duration_ms = FLOOR(EXTRACT(EPOCH FROM (now() - v_started_at)) * 1000)::integer
    WHERE id = v_log_id;
  EXCEPTION WHEN OTHERS THEN
    UPDATE public.user_attempt_stats_refresh_logs
    SET
      finished_at = now(),
      status = 'failed',
      duration_ms = FLOOR(EXTRACT(EPOCH FROM (now() - v_started_at)) * 1000)::integer,
      error_message = LEFT(SQLERRM, 1000)
    WHERE id = v_log_id;

    RAISE;
  END;
END;
$$;

DO $$
DECLARE
  scheduled_job_id bigint;
BEGIN
  FOR scheduled_job_id IN
    SELECT jobid
    FROM cron.job
    WHERE jobname = 'refresh-user-attempt-stats-mv'
  LOOP
    PERFORM cron.unschedule(scheduled_job_id);
  END LOOP;
END;
$$;

SELECT cron.schedule(
  'refresh-user-attempt-stats-mv',
  '*/5 * * * *',
  $$
  SELECT public.run_user_attempt_stats_refresh_job();
  $$
);

CREATE OR REPLACE FUNCTION public.get_admin_users_page(
  _page integer DEFAULT 1,
  _page_size integer DEFAULT 20,
  _search text DEFAULT NULL
)
RETURNS TABLE(
  rows jsonb,
  total_count bigint,
  stats_last_refreshed_at timestamptz
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_page integer := GREATEST(COALESCE(_page, 1), 1);
  v_page_size integer := LEAST(GREATEST(COALESCE(_page_size, 20), 1), 100);
  v_search text := NULLIF(BTRIM(_search), '');
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM user_roles ur
    WHERE ur.user_id = v_user_id
      AND ur.role = 'admin'
  ) THEN
    RAISE EXCEPTION 'Admin access required';
  END IF;

  RETURN QUERY
  WITH filtered_users AS (
    SELECT p.id, p.display_name, p.telegram_id, p.created_at, p.updated_at
    FROM profiles p
    WHERE v_search IS NULL
       OR p.display_name ILIKE '%' || v_search || '%'
       OR p.telegram_id ILIKE '%' || v_search || '%'
  ),
  users_with_total AS (
    SELECT fu.*, COUNT(*) OVER() AS total_count
    FROM filtered_users fu
  ),
  paged_users AS (
    SELECT *
    FROM users_with_total
    ORDER BY created_at DESC
    LIMIT v_page_size
    OFFSET (v_page - 1) * v_page_size
  ),
  mv_stats AS (
    SELECT
      pu.id AS user_id,
      mv.attempt_count,
      mv.correct_count
    FROM paged_users pu
    LEFT JOIN public.user_attempt_stats_mv mv ON mv.user_id = pu.id
  ),
  missing_mv_users AS (
    SELECT ms.user_id
    FROM mv_stats ms
    WHERE ms.attempt_count IS NULL
  ),
  attempt_stats_live AS (
    SELECT al.user_id,
           COUNT(*)::bigint AS attempt_count,
           COUNT(*) FILTER (WHERE al.is_correct = true)::bigint AS correct_count
    FROM missing_mv_users mmu
    JOIN attempt_logs al ON al.user_id = mmu.user_id
    GROUP BY al.user_id
  ),
  attempt_stats AS (
    SELECT
      ms.user_id,
      COALESCE(ms.attempt_count, asl.attempt_count, 0)::bigint AS attempt_count,
      COALESCE(ms.correct_count, asl.correct_count, 0)::bigint AS correct_count
    FROM mv_stats ms
    LEFT JOIN attempt_stats_live asl ON asl.user_id = ms.user_id
  ),
  latest_refresh AS (
    SELECT MAX(finished_at) AS stats_last_refreshed_at
    FROM public.user_attempt_stats_refresh_logs
    WHERE status = 'success'
  )
  SELECT
    COALESCE(
      jsonb_agg(
        jsonb_build_object(
          'id', pu.id,
          'display_name', pu.display_name,
          'telegram_id', pu.telegram_id,
          'created_at', pu.created_at,
          'updated_at', pu.updated_at,
          'attempt_count', COALESCE(ast.attempt_count, 0),
          'correct_count', COALESCE(ast.correct_count, 0),
          'is_admin', EXISTS (
            SELECT 1
            FROM user_roles ur
            WHERE ur.user_id = pu.id
              AND ur.role = 'admin'
          ),
          'subscription', CASE
            WHEN s.user_id IS NULL THEN NULL
            ELSE jsonb_build_object(
              'plan', s.plan,
              'expires_at', s.expires_at,
              'is_active', s.is_active,
              'duration', s.duration
            )
          END
        )
        ORDER BY pu.created_at DESC
      ),
      '[]'::jsonb
    ) AS rows,
    COALESCE(MAX(pu.total_count), 0)::bigint AS total_count,
    (SELECT lr.stats_last_refreshed_at FROM latest_refresh lr) AS stats_last_refreshed_at
  FROM paged_users pu
  LEFT JOIN attempt_stats ast ON ast.user_id = pu.id
  LEFT JOIN subscriptions s ON s.user_id = pu.id;
END;
$$;

REVOKE ALL ON FUNCTION public.run_user_attempt_stats_refresh_job() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.run_user_attempt_stats_refresh_job() TO service_role;
